### PR TITLE
Pretty tweets

### PR DESCRIPTION
**Pull request by rock3r**
Prettified tweets fragment :)

### CODE REVIEW

**Comment by rock3r** [comment]
Just noticed a couple small fixes to do, please don't merge this yet! 

Sorry, I completely missed them this afternoon...

**Comment by rock3r** [comment]
Ok @alsutton, you can merge now! Everything's fixed :)

**Comment by alsutton** [comment]
Merged. Thanks :) (now I have to test it)

**Comment by rock3r** [comment]
Yes indeed :) Especially on 10" tablets. Works just fine on my Nexus 4 and
Nexus 7 (2012), Android 4.2.2.

**Pull request merged**
